answers for lesson 1
Code-the-Dream-School/node-express-course pull request #171
Opened 2024-02-27 05:39 UTC by IrynaLyakhova

2024-03-01 17:42 UTC, ethanarns requested changes
Excellent work! Only a few minor issues were found in the submitted files, good job. However, you seem to be missing prompter.js, could you complete that assignment, and then resubmit this?

2024-03-01 17:42 UTC, ethanarns commented on 01-node-tutorial/answers/11-fs-async.js
> +    console.log("Done with this task")
You got the command correct, however, there needs to be more writeFile calls in the callback

2024-03-01 17:42 UTC, ethanarns commented on 01-node-tutorial/answers/12-http.js
> +server.listen(5000)
Make sure to change the port value!

2024-03-03 03:42 UTC, IrynaLyakhova commented
@ethanarns thanks for the review! I've addressed your comments, please take another look.

2024-06-20 01:35 UTC, closed without merging